CREATE EXTERNAL TABLE IF NOT EXISTS pdb.fd_vb_order_info(
    value STRING
) 
PARTITIONED BY (pt STRING,hour STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001'
STORED AS TEXTFILE
LOCATION 's3://bigdata-offline/warehouse/pdb/order_info';


