CREATE TABLE `merchant_refund_week`  (
                                          `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
                                          `mct_id` int(11) NOT NULL COMMENT '商品所属商家',
                                          `first_cat_id` int(11) NOT NULL COMMENT '商品一级类目id，-1表示全部',
                                          `country` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '国家code,\"00\"表示全部',
                                          `shipping_type` tinyint(4) NOT NULL COMMENT '物流渠道,[全部，平邮，非平邮，集运] 按序对应0123',
                                          `count_date` date NOT NULL COMMENT '统计日期,每月1号日期',
                                          `refund_amount` decimal(15, 2) NOT NULL COMMENT '退款金额',
                                          `refund_number` int(11) NOT NULL COMMENT '退款子订单数',
                                          `refund_rate` decimal(15, 4) NOT NULL COMMENT '退款率',
                                          `refund_rate_item_dont_fit` decimal(15, 4) NOT NULL COMMENT '商品不合适退款率',
                                          `refund_rate_poor_quality` decimal(15, 4) NOT NULL COMMENT '质量差退款率',
                                          `refund_rate_item_not_as_described` decimal(15, 4) NOT NULL COMMENT '与描述不符退款率',
                                          `refund_rate_defective_item` decimal(15, 4) NOT NULL COMMENT '损坏退款率',
                                          `refund_rate_shipment_late` decimal(15, 4) NOT NULL COMMENT '晚发货退款率',
                                          `refund_rate_wrong_product` decimal(15, 4) NOT NULL COMMENT '错误商品退款率',
                                          `refund_rate_wrong_quantity` decimal(15, 4) NOT NULL COMMENT '错误数量退款率',
                                          `refund_rate_not_receive` decimal(15, 4) NOT NULL COMMENT '未收到退款率',
                                          `refund_rate_others` decimal(15, 4) NOT NULL COMMENT '其他退款率',
                                          `refund_rate_empty_package` decimal(15, 4) NOT NULL COMMENT '空包裹退款率',
                                          `create_time` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
                                          `update_time` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0),
                                          PRIMARY KEY (`id`) USING BTREE,
                                          UNIQUE INDEX `uk`(`mct_id`, `first_cat_id`, `country`, `shipping_type`, `count_date`) USING BTREE COMMENT 'mct+cat+country+ship+日期唯一确定一条统计数据'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '退款率表现-按周' ROW_FORMAT = Dynamic;