CREATE TABLE IF NOT EXISTS ods_fd_vb.ods_fd_order_goods_inc (
    rec_id bigint,
    order_id bigint,
    goods_style_id bigint COMMENT '@see goods_style.goods_style_id',
    sku STRING COMMENT '@see gods_style.sku',
    sku_id bigint COMMENT '@see goods_sku.sku_id',
    goods_id bigint,
    goods_name STRING,
    goods_sn STRING,
    goods_sku STRING COMMENT '商品 sku',
    goods_number bigint,
    market_price decimal(15, 4),
    shop_price decimal(15, 4),
    shop_price_exchange decimal(15, 4) COMMENT '价格转换后的数额',
    shop_price_amount_exchange decimal(15, 4) COMMENT '总额的转换后数值',
    bonus decimal(15, 4) COMMENT '该商品的折扣，负值；可能来自分类折扣或该商品折扣',
    coupon_code STRING COMMENT '优惠券代码',
    goods_attr STRING,
    send_number bigint,
    is_real bigint,
    extension_code STRING,
    parent_id bigint,
    is_gift bigint,
    goods_status bigint,
    action_amt decimal(15, 4),
    action_reason_cat bigint,
    action_note STRING,
    carrier_bill_id bigint,
    provider_id bigint,
    invoice_num STRING,
    return_points bigint,
    return_bonus STRING,
    biaoju_store_goods_id bigint,
    subtitle STRING,
    addtional_shipping_fee bigint,
    style_id bigint,
    customized STRING COMMENT '表示移动定制机信息',
    status_id STRING COMMENT '商品新旧状态',
    added_fee decimal(15, 4) COMMENT '税率',
    custom_fee decimal(15, 4) COMMENT '自定义尺寸的费用',
    custom_fee_exchange decimal(15, 4),
    plussize_fee decimal(15, 4) COMMENT '大尺码加钱',
    plussize_fee_exchange decimal(15, 4),
    rush_order_fee decimal(15, 4) COMMENT 'rush order fee',
    rush_order_fee_exchange decimal(15, 4) COMMENT 'rush order fee',
    coupon_goods_id bigint,
    coupon_cat_id bigint,
    coupon_config_value decimal(15, 4) COMMENT '@see ok_coupon_config',
    coupon_config_coupon_type STRING COMMENT '@see ok_coupon_config',
    styles STRING COMMENT '用户选择或输入的各种样式，json；记录备查',
    img_type STRING COMMENT '默认图类型',
    goods_gallery STRING COMMENT '下单时产品显示图',
    goods_price_original decimal(15, 4) COMMENT '商品未添加任何附加费的价格',
    wrap_price decimal(15, 4) COMMENT '披肩美元价格',
    wrap_price_exchange decimal(15, 4) COMMENT '当前下单使用币种转换后的披肩价格',
    display_shop_price_exchange decimal(15, 4) COMMENT '显示用商品单价',
    display_shop_price_amount_exchange decimal(15, 4) COMMENT '显示用商品总金额费',
    display_custom_fee_exchange decimal(15, 4) COMMENT '显示用自定义尺寸费',
    display_plussize_fee_exchange decimal(15, 4) COMMENT '显示用加大码费',
    display_rush_order_fee_exchange decimal(15, 4) COMMENT '显示用加急费',
    display_wrap_price_exchange decimal(15, 4) COMMENT '显示用披肩费',
    heel_type_price decimal(15, 4) COMMENT '鞋跟定制费用',
    heel_type_price_exchange decimal(15, 4) COMMENT '鞋跟定制支付币种费用',
    display_heel_type_price_exchange decimal(15, 4) COMMENT '鞋跟定制支付币种显示费用'
) COMMENT '来自kafka订单商品每日增量数据'
PARTITIONED BY (pt STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001'
STORED AS PARQUETFILE
;

CREATE TABLE IF NOT EXISTS ods_fd_vb.ods_fd_order_goods_binlog_inc (
    rec_id bigint,
    order_id bigint,
    goods_style_id bigint COMMENT '@see goods_style.goods_style_id',
    sku STRING COMMENT '@see gods_style.sku',
    sku_id bigint COMMENT '@see goods_sku.sku_id',
    goods_id bigint,
    goods_name STRING,
    goods_sn STRING,
    goods_sku STRING COMMENT '商品 sku',
    goods_number bigint,
    market_price decimal(15, 4),
    shop_price decimal(15, 4),
    shop_price_exchange decimal(15, 4) COMMENT '价格转换后的数额',
    shop_price_amount_exchange decimal(15, 4) COMMENT '总额的转换后数值',
    bonus decimal(15, 4) COMMENT '该商品的折扣，负值；可能来自分类折扣或该商品折扣',
    coupon_code STRING COMMENT '优惠券代码',
    goods_attr STRING,
    send_number bigint,
    is_real bigint,
    extension_code STRING,
    parent_id bigint,
    is_gift bigint,
    goods_status bigint,
    action_amt decimal(15, 4),
    action_reason_cat bigint,
    action_note STRING,
    carrier_bill_id bigint,
    provider_id bigint,
    invoice_num STRING,
    return_points bigint,
    return_bonus STRING,
    biaoju_store_goods_id bigint,
    subtitle STRING,
    addtional_shipping_fee bigint,
    style_id bigint,
    customized STRING COMMENT '表示移动定制机信息',
    status_id STRING COMMENT '商品新旧状态',
    added_fee decimal(15, 4) COMMENT '税率',
    custom_fee decimal(15, 4) COMMENT '自定义尺寸的费用',
    custom_fee_exchange decimal(15, 4),
    plussize_fee decimal(15, 4) COMMENT '大尺码加钱',
    plussize_fee_exchange decimal(15, 4),
    rush_order_fee decimal(15, 4) COMMENT 'rush order fee',
    rush_order_fee_exchange decimal(15, 4) COMMENT 'rush order fee',
    coupon_goods_id bigint,
    coupon_cat_id bigint,
    coupon_config_value decimal(15, 4) COMMENT '@see ok_coupon_config',
    coupon_config_coupon_type STRING COMMENT '@see ok_coupon_config',
    styles STRING COMMENT '用户选择或输入的各种样式，json；记录备查',
    img_type STRING COMMENT '默认图类型',
    goods_gallery STRING COMMENT '下单时产品显示图',
    goods_price_original decimal(15, 4) COMMENT '商品未添加任何附加费的价格',
    wrap_price decimal(15, 4) COMMENT '披肩美元价格',
    wrap_price_exchange decimal(15, 4) COMMENT '当前下单使用币种转换后的披肩价格',
    display_shop_price_exchange decimal(15, 4) COMMENT '显示用商品单价',
    display_shop_price_amount_exchange decimal(15, 4) COMMENT '显示用商品总金额费',
    display_custom_fee_exchange decimal(15, 4) COMMENT '显示用自定义尺寸费',
    display_plussize_fee_exchange decimal(15, 4) COMMENT '显示用加大码费',
    display_rush_order_fee_exchange decimal(15, 4) COMMENT '显示用加急费',
    display_wrap_price_exchange decimal(15, 4) COMMENT '显示用披肩费',
    heel_type_price decimal(15, 4) COMMENT '鞋跟定制费用',
    heel_type_price_exchange decimal(15, 4) COMMENT '鞋跟定制支付币种费用',
    display_heel_type_price_exchange decimal(15, 4) COMMENT '鞋跟定制支付币种显示费用'
) COMMENT '来自kafka订单商品每日增量数据'
PARTITIONED BY (pt STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001'
STORED AS PARQUETFILE
;

CREATE TABLE IF NOT EXISTS ods_fd_vb.ods_fd_order_goods_arc (
    rec_id bigint,
    order_id bigint,
    goods_style_id bigint COMMENT '@see goods_style.goods_style_id',
    sku STRING COMMENT '@see gods_style.sku',
    sku_id bigint COMMENT '@see goods_sku.sku_id',
    goods_id bigint,
    goods_name STRING,
    goods_sn STRING,
    goods_sku STRING COMMENT '商品 sku',
    goods_number bigint,
    market_price decimal(15, 4),
    shop_price decimal(15, 4),
    shop_price_exchange decimal(15, 4) COMMENT '价格转换后的数额',
    shop_price_amount_exchange decimal(15, 4) COMMENT '总额的转换后数值',
    bonus decimal(15, 4) COMMENT '该商品的折扣，负值；可能来自分类折扣或该商品折扣',
    coupon_code STRING COMMENT '优惠券代码',
    goods_attr STRING,
    send_number bigint,
    is_real bigint,
    extension_code STRING,
    parent_id bigint,
    is_gift bigint,
    goods_status bigint,
    action_amt decimal(15, 4),
    action_reason_cat bigint,
    action_note STRING,
    carrier_bill_id bigint,
    provider_id bigint,
    invoice_num STRING,
    return_points bigint,
    return_bonus STRING,
    biaoju_store_goods_id bigint,
    subtitle STRING,
    addtional_shipping_fee bigint,
    style_id bigint,
    customized STRING COMMENT '表示移动定制机信息',
    status_id STRING COMMENT '商品新旧状态',
    added_fee decimal(15, 4) COMMENT '税率',
    custom_fee decimal(15, 4) COMMENT '自定义尺寸的费用',
    custom_fee_exchange decimal(15, 4),
    plussize_fee decimal(15, 4) COMMENT '大尺码加钱',
    plussize_fee_exchange decimal(15, 4),
    rush_order_fee decimal(15, 4) COMMENT 'rush order fee',
    rush_order_fee_exchange decimal(15, 4) COMMENT 'rush order fee',
    coupon_goods_id bigint,
    coupon_cat_id bigint,
    coupon_config_value decimal(15, 4) COMMENT '@see ok_coupon_config',
    coupon_config_coupon_type STRING COMMENT '@see ok_coupon_config',
    styles STRING COMMENT '用户选择或输入的各种样式，json；记录备查',
    img_type STRING COMMENT '默认图类型',
    goods_gallery STRING COMMENT '下单时产品显示图',
    goods_price_original decimal(15, 4) COMMENT '商品未添加任何附加费的价格',
    wrap_price decimal(15, 4) COMMENT '披肩美元价格',
    wrap_price_exchange decimal(15, 4) COMMENT '当前下单使用币种转换后的披肩价格',
    display_shop_price_exchange decimal(15, 4) COMMENT '显示用商品单价',
    display_shop_price_amount_exchange decimal(15, 4) COMMENT '显示用商品总金额费',
    display_custom_fee_exchange decimal(15, 4) COMMENT '显示用自定义尺寸费',
    display_plussize_fee_exchange decimal(15, 4) COMMENT '显示用加大码费',
    display_rush_order_fee_exchange decimal(15, 4) COMMENT '显示用加急费',
    display_wrap_price_exchange decimal(15, 4) COMMENT '显示用披肩费',
    heel_type_price decimal(15, 4) COMMENT '鞋跟定制费用',
    heel_type_price_exchange decimal(15, 4) COMMENT '鞋跟定制支付币种费用',
    display_heel_type_price_exchange decimal(15, 4) COMMENT '鞋跟定制支付币种显示费用'
) COMMENT '来自kafka订单商品每日增量数据'
PARTITIONED BY (pt STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001'
STORED AS PARQUETFILE;

CREATE TABLE IF NOT EXISTS ods_fd_vb.ods_fd_order_goods (
    rec_id bigint,
    order_id bigint,
    goods_style_id bigint COMMENT '@see goods_style.goods_style_id',
    sku STRING COMMENT '@see gods_style.sku',
    sku_id bigint COMMENT '@see goods_sku.sku_id',
    goods_id bigint,
    goods_name STRING,
    goods_sn STRING,
    goods_sku STRING COMMENT '商品 sku',
    goods_number bigint,
    market_price decimal(15, 4),
    shop_price decimal(15, 4),
    shop_price_exchange decimal(15, 4) COMMENT '价格转换后的数额',
    shop_price_amount_exchange decimal(15, 4) COMMENT '总额的转换后数值',
    bonus decimal(15, 4) COMMENT '该商品的折扣，负值；可能来自分类折扣或该商品折扣',
    coupon_code STRING COMMENT '优惠券代码',
    goods_attr STRING,
    send_number bigint,
    is_real bigint,
    extension_code STRING,
    parent_id bigint,
    is_gift bigint,
    goods_status bigint,
    action_amt decimal(15, 4),
    action_reason_cat bigint,
    action_note STRING,
    carrier_bill_id bigint,
    provider_id bigint,
    invoice_num STRING,
    return_points bigint,
    return_bonus STRING,
    biaoju_store_goods_id bigint,
    subtitle STRING,
    addtional_shipping_fee bigint,
    style_id bigint,
    customized STRING COMMENT '表示移动定制机信息',
    status_id STRING COMMENT '商品新旧状态',
    added_fee decimal(15, 4) COMMENT '税率',
    custom_fee decimal(15, 4) COMMENT '自定义尺寸的费用',
    custom_fee_exchange decimal(15, 4),
    plussize_fee decimal(15, 4) COMMENT '大尺码加钱',
    plussize_fee_exchange decimal(15, 4),
    rush_order_fee decimal(15, 4) COMMENT 'rush order fee',
    rush_order_fee_exchange decimal(15, 4) COMMENT 'rush order fee',
    coupon_goods_id bigint,
    coupon_cat_id bigint,
    coupon_config_value decimal(15, 4) COMMENT '@see ok_coupon_config',
    coupon_config_coupon_type STRING COMMENT '@see ok_coupon_config',
    styles STRING COMMENT '用户选择或输入的各种样式，json；记录备查',
    img_type STRING COMMENT '默认图类型',
    goods_gallery STRING COMMENT '下单时产品显示图',
    goods_price_original decimal(15, 4) COMMENT '商品未添加任何附加费的价格',
    wrap_price decimal(15, 4) COMMENT '披肩美元价格',
    wrap_price_exchange decimal(15, 4) COMMENT '当前下单使用币种转换后的披肩价格',
    display_shop_price_exchange decimal(15, 4) COMMENT '显示用商品单价',
    display_shop_price_amount_exchange decimal(15, 4) COMMENT '显示用商品总金额费',
    display_custom_fee_exchange decimal(15, 4) COMMENT '显示用自定义尺寸费',
    display_plussize_fee_exchange decimal(15, 4) COMMENT '显示用加大码费',
    display_rush_order_fee_exchange decimal(15, 4) COMMENT '显示用加急费',
    display_wrap_price_exchange decimal(15, 4) COMMENT '显示用披肩费',
    heel_type_price decimal(15, 4) COMMENT '鞋跟定制费用',
    heel_type_price_exchange decimal(15, 4) COMMENT '鞋跟定制支付币种费用',
    display_heel_type_price_exchange decimal(15, 4) COMMENT '鞋跟定制支付币种显示费用'
) COMMENT '来自arc当日全量订单商品数据'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001'
STORED AS PARQUETFILE;