
insert overwrite table dwd.dwd_vova_log_common_click_arc PARTITION (pt='2020-12-18', hour='23')
select
  event_fingerprint    ,
  datasource           ,
  event_name           ,
  platform             ,
  unix_timestamp(collector_tstamp)*1000    collector_tstamp     ,
  unix_timestamp(dvce_created_tstamp)*1000 dvce_created_tstamp  ,
  unix_timestamp(derived_tstamp)*1000      derived_tstamp       ,
  null collector_ts         ,
  null dvce_created_ts      ,
  name_tracker         ,
  buyer_id             ,
  domain_userid        ,
  language             ,
  country              ,
  geo_country          ,
  geo_city             ,
  null geo_region           ,
  null geo_latitude         ,
  null geo_longitude        ,
  null geo_region_name      ,
  null geo_timezone         ,
  currency             ,
  page_code            ,
  gender               ,
  page_url             ,
  account_class        ,
  channel_type         ,
  app_version          ,
  device_model         ,
  device_id            ,
  referrer             ,
  organic_idfv         ,
  advertising_id       ,
  advertising_id_sp    ,
  test_info            ,
  media_source         ,
  sys_lang             ,
  sys_country          ,
  vpn                  ,
  email                ,
  latlng               ,
  root                 ,
  is_tablet            ,
  os_type              ,
  os_version           ,
  ip                   ,
  element_name         ,
  element_url          ,
  element_content      ,
  list_uri             ,
  list_name            ,
  element_id           ,
  element_type         ,
  element_position     ,
  session_id           ,
  app_uri              ,
  landing_page         ,
  imsi                 ,
  null br_family       ,
  null br_version
from
dwd.dwd_vova_log_common_click_arc_history
where pt ='2020-12-18' and hour='23'


******************************************************************************************

insert overwrite table dwd.dwd_vova_log_click_arc PARTITION (pt='2020-12-18', hour='23')
select
  event_fingerprint   ,
  datasource          ,
  event_name          ,
  platform            ,
  unix_timestamp(collector_tstamp)*1000    collector_tstamp    ,
  unix_timestamp(dvce_created_tstamp)*1000 dvce_created_tstamp ,
  unix_timestamp(derived_tstamp)*1000      derived_tstamp      ,
  null collector_ts        ,
  null dvce_created_ts     ,
  name_tracker        ,
  buyer_id            ,
  domain_userid       ,
  language            ,
  country             ,
  geo_country         ,
  geo_city            ,
  null geo_region          ,
  null geo_latitude        ,
  null geo_longitude       ,
  null geo_region_name     ,
  null geo_timezone        ,
  currency            ,
  page_code           ,
  gender              ,
  page_url            ,
  account_class       ,
  channel_type        ,
  app_version         ,
  device_model        ,
  device_id           ,
  referrer            ,
  organic_idfv        ,
  advertising_id      ,
  advertising_id_sp   ,
  test_info           ,
  media_source        ,
  sys_lang            ,
  sys_country         ,
  vpn                 ,
  email               ,
  latlng              ,
  root                ,
  is_tablet           ,
  os_type             ,
  os_version          ,
  ip                  ,
  session_id          ,
  app_uri             ,
  event_type          ,
  list_type           ,
  element_id          ,
  element_name        ,
  element_type        ,
  element_position    ,
  brand_id            ,
  recall_pool         ,
  list_uri            ,
  extra               ,
  landing_page        ,
  imsi                ,
  null br_family      ,
  null br_version
from
dwd.dwd_vova_log_click_arc_history
where pt ='2020-12-18' and hour='23'

******************************************************************************************

insert overwrite table dwd.dwd_vova_log_data_arc PARTITION (pt='2020-12-18', hour='23')
select
  event_fingerprint     ,
  datasource            ,
  event_name            ,
  platform              ,
  unix_timestamp(collector_tstamp)*1000    collector_tstamp      ,
  unix_timestamp(dvce_created_tstamp)*1000 dvce_created_tstamp   ,
  unix_timestamp(derived_tstamp)*1000      derived_tstamp        ,
  null collector_ts          ,
  null dvce_created_ts       ,
  name_tracker          ,
  buyer_id              ,
  domain_userid         ,
  language              ,
  country               ,
  geo_country           ,
  geo_city              ,
  null geo_region            ,
  null geo_latitude          ,
  null geo_longitude         ,
  null geo_region_name       ,
  null geo_timezone          ,
  currency              ,
  page_code             ,
  gender                ,
  page_url              ,
  session_id            ,
  app_uri               ,
  account_class         ,
  channel_type          ,
  app_version           ,
  device_model          ,
  device_id             ,
  referrer              ,
  organic_idfv          ,
  advertising_id        ,
  advertising_id_sp     ,
  test_info             ,
  media_source          ,
  sys_lang              ,
  sys_country           ,
  vpn                   ,
  email                 ,
  latlng                ,
  root                  ,
  is_tablet             ,
  os_type               ,
  os_version            ,
  ip                    ,
  element_name          ,
  extra                 ,
  element_id            ,
  landing_page          ,
  imsi                  ,
  null br_family      ,
  null br_version
from
dwd.dwd_vova_log_data_arc_history
where pt ='2020-12-18' and hour='23'

******************************************************************************************

insert overwrite table dwd.dwd_vova_log_goods_click_arc PARTITION (pt='2020-12-18', hour='23')
select
  event_fingerprint         ,
  datasource                ,
  event_name                ,
  platform                  ,
  unix_timestamp(collector_tstamp)*1000    collector_tstamp          ,
  unix_timestamp(dvce_created_tstamp)*1000 dvce_created_tstamp       ,
  unix_timestamp(derived_tstamp)*1000      derived_tstamp            ,
  NULL collector_ts              ,
  NULL dvce_created_ts           ,
  name_tracker              ,
  buyer_id                  ,
  domain_userid             ,
  language                  ,
  country                   ,
  geo_country               ,
  geo_city                  ,
  NULL geo_region                ,
  NULL geo_latitude              ,
  NULL geo_longitude             ,
  NULL geo_region_name           ,
  NULL geo_timezone              ,
  currency                  ,
  page_code                 ,
  gender                    ,
  page_url                  ,
  account_class             ,
  channel_type              ,
  app_version               ,
  device_model              ,
  device_id                 ,
  referrer                  ,
  organic_idfv              ,
  advertising_id            ,
  advertising_id_sp         ,
  test_info                 ,
  media_source              ,
  sys_lang                  ,
  sys_country               ,
  vpn                       ,
  email                     ,
  latlng                    ,
  root                      ,
  is_tablet                 ,
  os_type                   ,
  os_version                ,
  ip                        ,
  list_uri                  ,
  list_type                 ,
  virtual_goods_id          ,
  absolute_position         ,
  element_url               ,
  recall_pool               ,
  element_type              ,
  session_id                ,
  app_uri                   ,
  landing_page              ,
  imsi                      ,
  null br_family      ,
  null br_version
from
dwd.dwd_vova_log_goods_click_arc_history
where pt ='2020-12-18' and hour='23'

******************************************************************************************

dwd_vova_log_common_impression_arc
insert overwrite table dwd.dwd_vova_log_common_impression_arc PARTITION (pt='2020-12-18', hour='23')
select
  event_fingerprint   ,
  datasource          ,
  event_name          ,
  platform            ,
  unix_timestamp(collector_tstamp)*1000    collector_tstamp    ,
  unix_timestamp(dvce_created_tstamp)*1000 dvce_created_tstamp ,
  unix_timestamp(derived_tstamp)*1000      derived_tstamp      ,
  null collector_ts        ,
  null dvce_created_ts     ,
  name_tracker        ,
  buyer_id            ,
  domain_userid       ,
  language            ,
  country             ,
  geo_country         ,
  geo_city            ,
  null geo_region          ,
  null geo_latitude        ,
  null geo_longitude       ,
  null geo_region_name     ,
  null geo_timezone        ,
  currency            ,
  page_code           ,
  gender              ,
  page_url            ,
  account_class       ,
  channel_type        ,
  app_version         ,
  device_model        ,
  device_id           ,
  referrer            ,
  organic_idfv        ,
  advertising_id      ,
  advertising_id_sp   ,
  test_info           ,
  media_source        ,
  sys_lang            ,
  sys_country         ,
  vpn                 ,
  email               ,
  latlng              ,
  root                ,
  is_tablet           ,
  os_type             ,
  os_version          ,
  ip                  ,
  list_uri            ,
  list_name           ,
  element_id          ,
  absolute_position   ,
  element_position    ,
  element_name        ,
  element_type        ,
  session_id          ,
  app_uri             ,
  landing_page        ,
  imsi                ,
  null br_family      ,
  null br_version
from
dwd.dwd_vova_log_common_impression_arc_history
where pt ='2020-12-18' and hour='23'


******************************************************************************************
dwd_vova_log_goods_impression_arc
insert overwrite table dwd.dwd_vova_log_goods_impression_arc PARTITION (pt='2020-12-18', hour='23')
select
  event_fingerprint   ,
  datasource          ,
  event_name          ,
  platform            ,
  unix_timestamp(collector_tstamp)*1000    collector_tstamp    ,
  unix_timestamp(dvce_created_tstamp)*1000 dvce_created_tstamp ,
  unix_timestamp(derived_tstamp)*1000      derived_tstamp      ,
  null collector_ts        ,
  null dvce_created_ts     ,
  name_tracker        ,
  buyer_id            ,
  domain_userid       ,
  language            ,
  country             ,
  geo_country         ,
  geo_city            ,
  null geo_region          ,
  null geo_latitude        ,
  null geo_longitude       ,
  null geo_region_name     ,
  null geo_timezone        ,
  currency            ,
  page_code           ,
  gender              ,
  page_url            ,
  account_class       ,
  channel_type        ,
  app_version         ,
  device_model        ,
  device_id           ,
  referrer            ,
  organic_idfv        ,
  advertising_id      ,
  advertising_id_sp   ,
  test_info           ,
  media_source        ,
  sys_lang            ,
  sys_country         ,
  vpn                 ,
  email               ,
  latlng              ,
  root                ,
  is_tablet           ,
  os_type             ,
  os_version          ,
  ip                  ,
  list_uri            ,
  list_type           ,
  virtual_goods_id    ,
  absolute_position   ,
  recall_pool         ,
  element_type        ,
  session_id          ,
  app_uri             ,
  landing_page        ,
  imsi                ,
  null br_family      ,
  null br_version
from
dwd.dwd_vova_log_goods_impression_arc_history
where pt ='2020-12-18' and hour='23'

******************************************************************************************
dwd_vova_log_impression_arc
insert overwrite table dwd.dwd_vova_log_impression_arc PARTITION (pt='2020-12-18', hour='23')
select
  event_fingerprint   ,
  datasource          ,
  event_name          ,
  platform            ,
  unix_timestamp(collector_tstamp)*1000    collector_tstamp    ,
  unix_timestamp(dvce_created_tstamp)*1000 dvce_created_tstamp ,
  unix_timestamp(derived_tstamp)*1000      derived_tstamp      ,
  null collector_ts        ,
  null dvce_created_ts     ,
  name_tracker        ,
  buyer_id            ,
  domain_userid       ,
  language            ,
  country             ,
  geo_country         ,
  geo_city            ,
  null geo_region          ,
  null geo_latitude        ,
  null geo_longitude       ,
  null geo_region_name     ,
  null geo_timezone        ,
  currency            ,
  page_code           ,
  gender              ,
  page_url            ,
  account_class       ,
  channel_type        ,
  app_version         ,
  device_model        ,
  device_id           ,
  referrer            ,
  organic_idfv        ,
  advertising_id      ,
  advertising_id_sp   ,
  test_info           ,
  media_source        ,
  sys_lang            ,
  sys_country         ,
  vpn                 ,
  email               ,
  latlng              ,
  root                ,
  is_tablet           ,
  os_type             ,
  os_version          ,
  ip                  ,
  app_uri             ,
  session_id          ,
  list_type           ,
  element_name        ,
  landing_page        ,
  imsi                ,
  null br_family      ,
  null br_version
from
dwd.dwd_vova_log_impression_arc_history
where pt ='2020-12-18' and hour='23'

******************************************************************************************
dwd_vova_log_impressions_arc
insert overwrite table dwd.dwd_vova_log_impressions_arc PARTITION (pt='2020-12-18', hour='23')
select
  event_fingerprint    ,
  datasource           ,
  event_name           ,
  platform             ,
  unix_timestamp(collector_tstamp)*1000    collector_tstamp     ,
  unix_timestamp(dvce_created_tstamp)*1000 dvce_created_tstamp  ,
  unix_timestamp(derived_tstamp)*1000      derived_tstamp       ,
  null collector_ts         ,
  null dvce_created_ts      ,
  name_tracker         ,
  buyer_id             ,
  domain_userid        ,
  language             ,
  country              ,
  geo_country          ,
  geo_city             ,
  null geo_region           ,
  null geo_latitude         ,
  null geo_longitude        ,
  null geo_region_name      ,
  null geo_timezone         ,
  currency             ,
  page_code            ,
  gender               ,
  page_url             ,
  account_class        ,
  channel_type         ,
  app_version          ,
  device_model         ,
  device_id            ,
  referrer             ,
  organic_idfv         ,
  advertising_id       ,
  advertising_id_sp    ,
  test_info            ,
  media_source         ,
  sys_lang             ,
  sys_country          ,
  vpn                  ,
  email                ,
  latlng               ,
  root                 ,
  is_tablet            ,
  os_type              ,
  os_version           ,
  ip                   ,
  session_id           ,
  app_uri              ,
  event_type           ,
  list_type            ,
  element_id           ,
  element_name         ,
  element_type         ,
  element_position     ,
  brand_id             ,
  recall_pool          ,
  list_uri             ,
  extra                ,
  landing_page         ,
  imsi                 ,
  null br_family      ,
  null br_version
from
dwd.dwd_vova_log_impressions_arc_history
where pt ='2020-12-18' and hour='23'

******************************************************************************************
dwd_vova_log_order_process_arc
insert overwrite table dwd.dwd_vova_log_order_process_arc PARTITION (pt='2020-12-18', hour='23')
select
  event_fingerprint      ,
  datasource             ,
  event_name             ,
  platform               ,
  unix_timestamp(collector_tstamp)*1000    collector_tstamp       ,
  unix_timestamp(dvce_created_tstamp)*1000 dvce_created_tstamp    ,
  unix_timestamp(derived_tstamp)*1000      derived_tstamp         ,
  null collector_ts           ,
  null dvce_created_ts        ,
  name_tracker           ,
  buyer_id               ,
  domain_userid          ,
  language               ,
  country                ,
  geo_country            ,
  geo_city               ,
  null geo_region             ,
  null geo_latitude           ,
  null geo_longitude          ,
  null geo_region_name        ,
  null geo_timezone           ,
  currency               ,
  page_code              ,
  gender                 ,
  page_url               ,
  account_class          ,
  channel_type           ,
  app_version            ,
  device_model           ,
  device_id              ,
  referrer               ,
  organic_idfv           ,
  advertising_id         ,
  advertising_id_sp      ,
  test_info              ,
  media_source           ,
  sys_lang               ,
  sys_country            ,
  vpn                    ,
  email                  ,
  latlng                 ,
  root                   ,
  is_tablet              ,
  os_type                ,
  os_version             ,
  ip                     ,
  element_name           ,
  submit_result          ,
  virtual_goods_id       ,
  payment_method         ,
  session_id             ,
  app_uri                ,
  landing_page           ,
  imsi                   ,
  null br_family      ,
  null br_version
from
dwd.dwd_vova_log_order_process_arc_history
where pt ='2020-12-18' and hour='23'

******************************************************************************************
dwd_vova_log_page_view_arc
insert overwrite table dwd.dwd_vova_log_page_view_arc PARTITION (pt='2020-12-18', hour='23')
select
  event_fingerprint   ,
  datasource          ,
  event_name          ,
  platform            ,
  unix_timestamp(collector_tstamp)*1000    collector_tstamp    ,
  unix_timestamp(dvce_created_tstamp)*1000 dvce_created_tstamp ,
  unix_timestamp(derived_tstamp)*1000      derived_tstamp      ,
  null collector_ts        ,
  null dvce_created_ts     ,
  name_tracker        ,
  buyer_id            ,
  domain_userid       ,
  language            ,
  country             ,
  geo_country         ,
  geo_city            ,
  null geo_region          ,
  null geo_latitude        ,
  null geo_longitude       ,
  null geo_region_name     ,
  null geo_timezone        ,
  currency            ,
  page_code           ,
  gender              ,
  page_url            ,
  account_class       ,
  channel_type        ,
  app_version         ,
  device_model        ,
  device_id           ,
  referrer            ,
  organic_idfv        ,
  advertising_id      ,
  advertising_id_sp   ,
  test_info           ,
  media_source        ,
  sys_lang            ,
  sys_country         ,
  vpn                 ,
  email               ,
  latlng              ,
  root                ,
  is_tablet           ,
  os_type             ,
  os_version          ,
  ip                  ,
  app_uri             ,
  session_id          ,
  view_type           ,
  virtual_goods_id    ,
  enter_ts            ,
  leave_ts            ,
  landing_page        ,
  imsi                ,
  null br_family      ,
  null br_version
from
dwd.dwd_vova_log_page_view_arc_history
where pt ='2020-12-18' and hour='23'

******************************************************************************************
dwd_vova_log_screen_view_arc
insert overwrite table dwd.dwd_vova_log_screen_view_arc PARTITION (pt='2020-12-18', hour='23')
select
  event_fingerprint     ,
  datasource            ,
  event_name            ,
  platform              ,
  unix_timestamp(collector_tstamp)*1000    collector_tstamp      ,
  unix_timestamp(dvce_created_tstamp)*1000 dvce_created_tstamp   ,
  unix_timestamp(derived_tstamp)*1000      derived_tstamp        ,
  null collector_ts          ,
  null dvce_created_ts       ,
  name_tracker          ,
  buyer_id              ,
  domain_userid         ,
  language              ,
  country               ,
  geo_country           ,
  geo_city              ,
  null geo_region            ,
  null geo_latitude          ,
  null geo_longitude         ,
  null geo_region_name       ,
  null geo_timezone          ,
  currency              ,
  page_code             ,
  gender                ,
  page_url              ,
  account_class         ,
  channel_type          ,
  view_type             ,
  app_version           ,
  device_model          ,
  device_id             ,
  referrer              ,
  organic_idfv          ,
  advertising_id        ,
  advertising_id_sp     ,
  test_info             ,
  media_source          ,
  sys_lang              ,
  sys_country           ,
  vpn                   ,
  email                 ,
  latlng                ,
  root                  ,
  is_tablet             ,
  os_type               ,
  os_version            ,
  ip                    ,
  session_id            ,
  virtual_goods_id      ,
  app_uri               ,
  landing_page          ,
  imsi                  ,
  null br_family      ,
  null br_version
from
dwd.dwd_vova_log_screen_view_arc_history
where pt ='2020-12-18' and hour='23'
