drop table IF EXISTS dwd.dwd_vova_fact_log_impressions;
CREATE TABLE  IF NOT EXISTS dwd.dwd_vova_fact_log_impressions
(
    event_fingerprint   STRING COMMENT '??????',
    datasource          STRING COMMENT '?????vova|ac',
    event_name          STRING COMMENT '???',
    platform            STRING COMMENT '???web|mob',
    collector_tstamp    STRING COMMENT '????????????',
    dvce_created_tstamp STRING COMMENT '????????',
    derived_tstamp      STRING COMMENT '?????????????',
    name_tracker        STRING COMMENT '',
    buyer_id            BIGINT COMMENT '??id',
    domain_userid       STRING COMMENT '',
    language            STRING COMMENT '??',
    country             STRING COMMENT '??',
    geo_country         STRING COMMENT 'snowplow????',
    geo_city            STRING COMMENT 'snowplow????',
    currency            STRING COMMENT 'snowplow????',
    page_code           STRING COMMENT '??',
    gender              STRING COMMENT '??',
    page_url            STRING COMMENT '????',
    account_class       STRING COMMENT '',
    channel_type        STRING COMMENT '',
    app_version         STRING COMMENT 'app???',
    device_model        STRING COMMENT '????',
    device_id           STRING COMMENT '??id',
    referrer            STRING COMMENT '',
    organic_idfv        STRING COMMENT '',
    advertising_id      STRING COMMENT '',
    advertising_id_sp   STRING COMMENT '',
    test_info           STRING COMMENT '????',
    media_source        STRING COMMENT '',
    sys_lang            STRING COMMENT '????',
    sys_country         STRING COMMENT '????',
    vpn                 STRING COMMENT '????vpn',
    email               STRING COMMENT '??',
    latlng              STRING COMMENT '',
    root                STRING COMMENT '',
    is_tablet           STRING COMMENT '?????',
    os_type             STRING COMMENT '????,ios|android',
    os_version          STRING COMMENT '?????',
    ip                  STRING COMMENT 'ip',
    session_id          STRING COMMENT 'session_id',
    app_uri             STRING COMMENT 'app_uri',
    list_type           STRING COMMENT 'list_type',
    element_id          STRING COMMENT '??id',
    element_name        STRING COMMENT '????',
    element_type        STRING COMMENT '????',
    element_position    STRING COMMENT '????',
    extra               STRING COMMENT '????',
    landing_page        STRING,
    imsi                STRING
)
    PARTITIONED BY (pt STRING) row format delimited fields terminated by '\001' stored as parquetfile;